### Difference between List multiplication and NumPy Multiplication

In [2]:
import numpy as np
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.10242462158203125

 Numpy operation time:  0.007292509078979492


### Creating array from scratch

In [16]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)

full = np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0, 11, 2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.69783091 0.92574662 0.35570728]
 [0.91506968 0.94097295 0.2275598 ]]
sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [27]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor: \n",tensor)

Vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [3]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape:",arr.shape)
print("Dimention:",arr.ndim)
print("Size:",arr.size)
print("DType:",arr.dtype)

Shape: (2, 3)
Dimention: 2
Size: 6
DType: int64
