In [9]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7])
print(f"Basic Slicking :- {arr[2:7]}")
print(f"with step Slicking :- {arr[1:8:2]}")
print(f"Negative Slicing :- {arr[-3]}")

Basic Slicking :- [3 4 5 6 7]
with step Slicking :- [2 4 6]
Negative Slicing :- 5


In [24]:
arr_2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(f"Specific element:- {arr_2d[1,2]}")
print(f"Entire Row:- {arr_2d[:, 1]}")

Specific element:- 6
Entire Row:- [2 5 8]


## Sorting

In [ ]:
unSorted = np.array([3,4,5,6,7,8,1])
print(f"Sorted: {np.sort(unSorted)}")

array_2d_unsorted = np.array([[1,2],[4,10],[3,41]])
print(f"Sorted 2D by Column: {np.sort(array_2d_unsorted, axis=0)}")
print(f"Sorted 2D by Row: {np.sort(array_2d_unsorted, axis=1)}")

## Filter

In [26]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers % 2 == 0] # Note:- Write Expression in between array in numpy.
print(f"Even Number:- {even_number}")

Even Number:- [2 4 6 8]


## Filter with mask

In [31]:
mask = numbers > 5 # this type filteration work only in 'np'.
print(f"Numbers greather than 5: {numbers[mask]}")

Numbers greather than 5: [6 7 8 9]


## Indexing vs np.where()

In [35]:
indicies = [0,2,4]
print(numbers[indicies])

where_result = np.where(numbers > 5)
print(f"NP Where: {numbers[where_result]}")

[1 3 5]
NP Where: [6 7 8 9]


In [41]:
# if numbers > 5 --> numbers*4, else --> numbers in numpy
condition_array = np.where(numbers > 5, numbers*4, numbers)  ## first:-condition, second:if statement, third:else statemrnt
print(f"Condition Array:- {condition_array}")

Condition Array:- [ 1  2  3  4  5 24 28 32 36]


## Vstack && Hstack


In [42]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row)) # add new Row in vector.
print(original)
print(f"With New Row:- {with_new_row}")

new_col = np.array([[5],[6]])
with_new_col = np.hstack((original, new_col)) # add new Column in vector.
print(f"With New Column:- {with_new_col}")

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with_new Column:- [[1 2 5]
 [3 4 6]]
